name: Code Quality Check

on:
  push:
    branches:
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '9'

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java Version
        run: java -version

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Clear npm cache (optional)
        run: npm cache clean --force

      - name: Install ESLint latest version
        run: npm install eslint@9.13.0 --save-dev

      - name: Run ESLint for Code Style Check
        run: npx eslint . || exit 0

      - name: Code Quality Check with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}  # This should now point to the correct path
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=Kartik-yo
            -Dsonar.projectKey=Kartik-yo_code-quality-check
            -Dsonar.projectBaseDir=.
