name: Code Quality Check

on:
  push:
    branches:
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Using a stable Node.js version that supports modern ESLint

      - name: Install dependencies
        run: npm install --prefix ./path-to-subdirectory

      - name: Install dependencies
        run: npm install

      - name: Install ESLint latest version
        run: npm install eslint@latest --save-dev

      - name: Run ESLint for Code Style Check
        run: npx eslint index.js || exit 1  # Exits with 1 if ESLint finds issues

      - name: Code Quality Check with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=Kartik-yo
            -Dsonar.projectKey=Kartik-yo_code-quality-check
